Document: gst-plugin-pylon
Title: Debian gst-plugin-pylon Manual
Author: <insert document author here>
Abstract: This manual describes what gst-plugin-pylon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gst-plugin-pylon/gst-plugin-pylon.sgml.gz

Format: postscript
Files: /usr/share/doc/gst-plugin-pylon/gst-plugin-pylon.ps.gz

Format: text
Files: /usr/share/doc/gst-plugin-pylon/gst-plugin-pylon.text.gz

Format: HTML
Index: /usr/share/doc/gst-plugin-pylon/html/index.html
Files: /usr/share/doc/gst-plugin-pylon/html/*.html
